### PR TITLE
Fixed some styling issues on the login page

### PR DESCRIPTION
**Pull request by philippsander**
I try to contribute more to this repository. these are just some quick fixes i could do

### CODE REVIEW

**Comment by philippsander** [comment]
ok.... the project wont build with travis CI .... maybe the missing dependencies can be removed, since they should be provided by forever

**Comment by philippsander** [comment]
I'm really sorry for this messy pull request. I do not work with github that often.

**Comment by FGRibreau** [comment]
Hello @philippsander, 

no problem, test are green, I'm merging it :)

**Comment by FGRibreau** [comment]
@philippsander published in v0.2.0 :)

**Comment by philippsander** [comment]
awesome! thank you

**Pull request merged**
